export const FETCH_USER_REQUESTING = "FETCH_USER_REQUESTING";
export const FETCH_USER_SUCCESSFUL = "FETCH_USER_SUCCESSFUL";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const FETCH_THREADS_REQUESTING = "FETCH_THREADS_REQUESTING";
export const FETCH_THREADS_SUCCESSFUL = "FETCH_THREADS_SUCCESSFUL";
export const FETCH_THREADS_FAILED = "FETCH_THREADS_FAILED";
