export const FETCH_USER_REQUESTING = "FETCH_USER_REQUESTING";
export const FETCH_USER_SUCCESSFUL = "FETCH_USER_SUCCESSFUL";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const FETCH_THREADS_REQUESTING = "FETCH_THREADS_REQUESTING";
export const FETCH_THREADS_SUCCESSFUL = "FETCH_THREADS_SUCCESSFUL";
export const FETCH_THREADS_FAILED = "FETCH_THREADS_FAILED";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED"
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL"