export const RECEIVE_USER_FAILURE = 'RECEIVE_USER_FAILURE';
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER_SUCCESS';

export const FETCH_USER_REQUESTING = 'FETCH_USER_REQUESTING';
export const FETCH_USER_SUCCESSFUL = 'FETCH_USER_SUCCESSFUL';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
